### ISSUE TITLE
Plugin change default property name case

### ISSUE THREAD

**Issue by WuglyakBolgoink** [boneVidy/json2ts#17]
Is it possible not to change original case of property names?

what Backend send
![image](https://user-images.githubusercontent.com/2271337/117362074-1cc93d80-aebb-11eb-9126-21e4b9baf248.png)

what generate plugin
![image](https://user-images.githubusercontent.com/2271337/117362103-25ba0f00-aebb-11eb-8fe6-50bef26d50ad.png)

it should be 

```ts
export interface DocumentProperties {
  MAX_FILE_SIZE: number;
  ALLOWED_UPLOAD_SPACE: number;
}
```

**Comment by boneVidy** [comment]
fix in v1.0.29
