### ISSUE TITLE
cannot convert array to interface

### ISSUE THREAD

**Issue by WuglyakBolgoink** [boneVidy/json2ts#2]
if I put in window any array, then I got an error "Wrong JSON syntax"...

1. put an array into textarea block
2. select "interface" radio-button or "type", doesn't matters
3. set up interface/type name, for example `IDocs`

what expected:

1. create type `type iDocs[List] = iDocs[];`
2. create interface `iDocs { ... }`

----

⁉️ is it possible to do this?

**Comment by boneVidy** [comment]
> is it possible to do this?

I forgot to deal with the situation when the data is an array。
i will fix it.
