### ISSUE TITLE
右键的json2ts功能希望能直接插入到光标所在位置

### ISSUE THREAD

**Issue by FurryWolfX** [boneVidy/json2ts#4]
右键的json2ts功能希望能直接插入到光标所在位置。
目前是插入到文件底部，希望改进。

**Comment by WuglyakBolgoink** [comment]
@FurryWolfX  what the benefit of this case?

**Comment by FurryWolfX** [comment]
When a file has a lot of code, a way to organize the code quickly is needed instead of manually moving the code at the bottom of the file.

**Comment by boneVidy** [comment]
> When a file has a lot of code, a way to organize the code quickly is needed instead of manually moving the code at the bottom of the file.

下载最新的插件安装覆盖 就能解决这个问题了。
因为jetbrain 官方市场审核太慢，这个插件现在没有上传到官方市场了。请在https://github.com/boneVidy/json2ts/releases/tag/v1.0.11
下载最新版本，然后install from disk

**Comment by WuglyakBolgoink** [comment]
@boneVidy my last version is v1.0.6... heh... maybe it will be better to write in JB support?

**Comment by boneVidy** [comment]
> @boneVidy my last version is v1.0.6... heh... maybe it will be better to write in JB support?

The jetbrain review and audit time is very long, so it has not been uploaded to jetbtrain plugin market.you can [download ](https://github.com/boneVidy/json2ts/releases/download/v1.0.11/com.jsonts.kotlin-1.0.11.zip)and  install this plugin from disk
![image](https://user-images.githubusercontent.com/10415170/91111813-07590e00-e6b4-11ea-9a21-9891fdb4eb55.png)
