### ISSUE TITLE
无法使用，文件里填充了一些错误信息

### ISSUE THREAD

**Issue by PengleiYu** [boneVidy/json2ts#41]
<img width="1144" alt="image" src="https://user-images.githubusercontent.com/15772328/202660449-b457289a-93e7-4263-a220-25652a57dfd0.png">

**Comment by boneVidy** [comment]
> <img alt="image" width="1144" src="https://user-images.githubusercontent.com/15772328/202660449-b457289a-93e7-4263-a220-25652a57dfd0.png">

可否提供下插件版本还有输入的JSON参数
