### ISSUE TITLE
Wrong json syntax

### ISSUE THREAD

**Issue by WuglyakBolgoink** [boneVidy/json2ts#5]
Hallo @boneVidy !

I found again some strange error :-)

if my array has optional fields, then the plugin cannot generate interfaces and give me always `Wrong json syntax` message-dialog.

It will be great to have, maybe, some error exception code for detailed analyze...

**Comment by boneVidy** [comment]
> Hallo @boneVidy !
> 
> I found again some strange error :-)
> 
> if my array has optional fields, then the plugin cannot generate interfaces and give me always `Wrong json syntax` message-dialog.
> 
> It will be great to have, maybe, some error exception code for detailed analyze...

Pls write the input parameters, expected output results and actual output results in your reply
